//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endmer.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EndmerEntities : DbContext
    {
        public EndmerEntities()
            : base("name=EndmerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Departmanlar> Tbl_Departmanlar { get; set; }
        public virtual DbSet<Tbl_Kategoriler> Tbl_Kategoriler { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_Urunler> Tbl_Urunler { get; set; }
        public virtual DbSet<Tbl_Araclar> Tbl_Araclar { get; set; }
        public virtual DbSet<Tbl_AracKayit> Tbl_AracKayit { get; set; }
        public virtual DbSet<Tbl_Zimmetler> Tbl_Zimmetler { get; set; }
        public virtual DbSet<Tbl_Konumlar> Tbl_Konumlar { get; set; }
        public virtual DbSet<Tbl_ZimmetAktar> Tbl_ZimmetAktar { get; set; }
        public virtual DbSet<Tbl_BakimKayit> Tbl_BakimKayit { get; set; }
        public virtual DbSet<Tbl_Dokuman> Tbl_Dokuman { get; set; }
        public virtual DbSet<Tbl_DokumanKonu> Tbl_DokumanKonu { get; set; }
        public virtual DbSet<Tbl_DokumanResim> Tbl_DokumanResim { get; set; }
        public virtual DbSet<Tbl_Yetkiler> Tbl_Yetkiler { get; set; }
    }
}
