//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endmer.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Araclar()
        {
            this.Tbl_AracKayit = new HashSet<Tbl_AracKayit>();
            this.Tbl_BakimKayit = new HashSet<Tbl_BakimKayit>();
        }

        public int ID { get; set; }
        [MinLength(3, ErrorMessage = "En az 3 karakter girilmelidir!"), MaxLength(20, ErrorMessage = "En fazla 20 karakter girilebilir!")]
        public string PLAKA { get; set; }
        public Nullable<int> LOKASYON { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string RESIM { get; set; }
        [MinLength(1, ErrorMessage = "En az 1 karakter girilmelidir!"), MaxLength(20, ErrorMessage = "En fazla 20 karakter girilebilir!")]
        public string KM { get; set; }
        [MinLength(3, ErrorMessage = "En az 3 karakter girilmelidir!"), MaxLength(100, ErrorMessage = "En fazla 100 karakter girilebilir!")]
        public string MARKA { get; set; }
        public Nullable<int> KULLANICI { get; set; }
        public Nullable<System.DateTime> BAKIMZAMANI { get; set; }
        public Nullable<System.DateTime> GECMISBAKIM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AracKayit> Tbl_AracKayit { get; set; }
        public virtual Tbl_Konumlar Tbl_Konumlar { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BakimKayit> Tbl_BakimKayit { get; set; }


    }
}
