//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endmer.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Tbl_Dokuman
    {
        public int ID { get; set; }
        public string BASLIK { get; set; }
        [AllowHtml]
        public string ICERIK { get; set; }
        public Nullable<int> KONU { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual Tbl_DokumanKonu Tbl_DokumanKonu { get; set; }
    }
}
