//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endmer.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Zimmetler
    {
        public int ID { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> ZIMMET { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<int> KONUM { get; set; }
        [MinLength(3, ErrorMessage = "En az 3 karakter girilmelidir!"), MaxLength(10, ErrorMessage = "En fazla 10 karakter girilebilir!")]
        public string ADET { get; set; }
        public string ONAYMESAJ { get; set; }
        [MinLength(3, ErrorMessage = "En az 3 karakter girilmelidir!"), MaxLength(10, ErrorMessage = "En fazla 10 karakter girilebilir!")]
        public string ARIZALIADET { get; set; }
    
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
        public virtual Tbl_Konumlar Tbl_Konumlar { get; set; }
    }
}
